name: Validate Schemas

on:
  pull_request:
    paths:
      - "data-structures/**"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Snowplow CLI
        uses: snowplow-product/snowplow-cli-action@v2

      - name: Validate data structures
        run: snowplow-cli validate data-structures --data-structures-path ./data-structures
