name: Validate Schemas

on:
  pull_request:
    paths:
      - "data-structures/**"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: snowplow/setup-snowplow-cli@v1

      - name: Validate data structures
        run: snowplow-cli ds validate ./data-structures
